"""Standalone RAG benchmark for the AI service (HTTP-level, black-box).

Measures four things against a live stack and writes raw artifacts so every
number can be re-checked by hand:

  latency  - sequential requests to POST /api/ai/similar-tickets with per-stage
             breakdown (Ollama embedding / Qdrant search / unaccounted overhead),
             plus a separate LLM-generation probe via SSE POST /api/ai/chat
             (time-to-first-token, generation tail, and out-of-band retrieval
             attribution so embed/search/generation costs are separable).
  load     - sustained concurrent traffic (default 10 -> 25 -> 50 workers) against
             POST /api/ai/similar-tickets and/or streamed /api/ai/chat via
             --load-endpoint, reporting achieved requests/sec (plus tokens/s for
             chat) and how latency shifts vs the sequential run.
  quality  - recall@k / precision@k (k = 1, 3, 5, 10) and MRR over an eval set of
             (query, expected_ticket_id) pairs. Pairs are generated by having the
             chat LLM paraphrase titles of real CLOSED tickets sampled from the
             index, then cached to results/eval_set.jsonl (edit freely; delete or
             pass --regen-eval-set to rebuild).
  scale    - current point count of the collection with a per-doc_type breakdown;
             every run appends to results/scale_history.csv so growth becomes
             visible across repeated runs; deltas vs the newest runs >=7 and
             >=30 days old are reported once history allows.

The service exposes no per-stage tracing, so stage timings are produced by
replaying each stage out-of-band against the very same backends the service
uses (same models, same filters, same scan size). Quality is scored with a
production-equivalent query: scan Settings.similar_scan points, filter
doc_type=ticket + status=closed, group by ticket keeping the best chunk score,
rank by score descending - exactly what SimilarityService does.

Usage (from services/ai-service/, venv activated):

  python bench/bench_rag.py                          # everything, defaults
  python bench/bench_rag.py --sections latency,scale # quick subset
  python bench/bench_rag.py --seq-requests 30 --load-duration 5 --eval-size 10
  python bench/bench_rag.py --reindex-tickets        # refresh index first (Admin)

Environment overrides: AI_BASE_URL, OLLAMA_URL, QDRANT_URL, BENCH_AUTH_TOKEN.
"""

from __future__ import annotations

import argparse
import asyncio
import csv
import json
import math
import os
import random
import statistics
import time
from datetime import UTC, datetime, timedelta
from pathlib import Path

import httpx

# ===================== CONFIG =====================

AI_BASE_URL = "http://localhost:5090"
OLLAMA_URL = "http://localhost:11434"
QDRANT_URL = "http://localhost:6333"
COLLECTION_NAME = "helpdesk_index"

EMBEDDING_MODEL = "nomic-embed-text"
CHAT_MODEL = "llama3.2:3b"
VECTOR_SIZE = 768
SIMILAR_SCAN = 20  # mirrors Settings.similar_scan used by SimilarityService

REPO_ROOT = Path(__file__).resolve().parents[3]
JWT_PRIVATE_KEY_PATH = REPO_ROOT / "infra" / "certs" / "private.pem"
JWT_AUDIENCE = "it-helpdesk-api"
JWT_ISSUER = "it-helpdesk-identity"
JWT_TTL_SECONDS = 3600
JWT_SUBJECT = "benchmark-runner"
AUTH_TOKEN_ENV = "BENCH_AUTH_TOKEN"
ROLE_CLAIM = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"

SEQ_REQUESTS = 300
WARMUP_REQUESTS = 5
CHAT_PROBE_REQUESTS = 30
CONCURRENCY_LEVELS = [10, 25, 50]
LOAD_ENDPOINTS = ["similar"]
LOAD_DURATION_SECONDS = 30.0
REQUEST_TIMEOUT_SECONDS = 120.0

EVAL_SET_SIZE = 40
K_VALUES = [1, 3, 5, 10]
RANDOM_SEED = 42

RESULTS_DIR = Path(__file__).resolve().parent / "results"
EVAL_SET_PATH = RESULTS_DIR / "eval_set.jsonl"
SCALE_HISTORY_PATH = RESULTS_DIR / "scale_history.csv"

# Applied last so exported env vars win, mirroring eval/run_eval.py conventions.
AI_BASE_URL = os.environ.get("AI_BASE_URL", AI_BASE_URL)
OLLAMA_URL = os.environ.get("OLLAMA_URL", OLLAMA_URL)
QDRANT_URL = os.environ.get("QDRANT_URL", QDRANT_URL)

QUERY_POOL = [
    "i forgot my password and cannot log into my laptop",
    "vpn disconnects every few minutes when working from home",
    "outlook crashes whenever i open an email with attachments",
    "my printer jams on double sided printing",
    "laptop became extremely slow after the last update",
    "cannot connect to the office wifi on my phone",
    "how do i request access to the shared finance drive",
    "second monitor keeps flickering on and off",
    "keyboard some keys stopped working after coffee spill",
    "software install is blocked by administrator permissions",
    "getting too many phishing emails in my inbox",
    "blue screen error when docking my laptop",
    "mfa push notifications never arrive on my new phone",
    "teams audio cuts out during calls with headset",
    "battery drains within two hours even when idle",
    "usb dock not detecting external hard drive",
    "license for design tool expired cannot activate",
    "pop up warning says my computer is infected",
    "browser cannot reach internal wiki page connection refused",
    "restore deleted folder from last night backup",
    "new employee starter account not created yet",
    "projector in meeting room 4 shows no signal",
    "desk phone goes straight to voicemail for callers",
    "excel file locked by another user ghost session",
    "email quarantine release button does nothing",
]

TICKET_FILTER = {
    "must": [
        {"key": "doc_type", "match": {"value": "ticket"}},
        {"key": "status", "match": {"value": "closed"}},
    ]
}

DOC_TYPES = ["ticket", "comment", "kb"]

# ===================== small utilities =====================


def percentile(sorted_values: list[float], p: float) -> float:
    """Linear-interpolation percentile on a pre-sorted list (numpy-style)."""
    if not sorted_values:
        return float("nan")
    if len(sorted_values) == 1:
        return sorted_values[0]
    rank = (p / 100.0) * (len(sorted_values) - 1)
    low = math.floor(rank)
    high = math.ceil(rank)
    frac = rank - low
    return sorted_values[low] * (1.0 - frac) + sorted_values[high] * frac


def latency_stats(samples_ms: list[float]) -> dict[str, float]:
    ordered = sorted(samples_ms)
    if not ordered:
        return {key: float("nan") for key in ("n", "mean_ms", "p50_ms", "p95_ms", "p99_ms", "max_ms")}
    return {
        "n": len(ordered),
        "mean_ms": round(statistics.fmean(ordered), 1),
        "p50_ms": round(percentile(ordered, 50), 1),
        "p95_ms": round(percentile(ordered, 95), 1),
        "p99_ms": round(percentile(ordered, 99), 1),
        "max_ms": round(ordered[-1], 1),
    }


def print_table(title: str, headers: list[str], rows: list[list]) -> None:
    def fmt(cell) -> str:
        if isinstance(cell, float):
            return f"{cell:.1f}" if math.isfinite(cell) else "-"
        return str(cell)

    rendered = [[fmt(cell) for cell in row] for row in rows]
    widths = [
        max([len(headers[i])] + [len(r[i]) for r in rendered]) for i in range(len(headers))
    ]
    print(f"\n{title}")
    print(" | ".join(h.ljust(widths[i]) for i, h in enumerate(headers)))
    print("-+-".join("-" * w for w in widths))
    for row in rendered:
        print(" | ".join(cell.ljust(widths[i]) for i, cell in enumerate(row)))


def sanitize(obj):
    """Replace NaN/inf with None so the JSON artifact stays strictly valid."""
    if isinstance(obj, float):
        return obj if math.isfinite(obj) else None
    if isinstance(obj, dict):
        return {key: sanitize(value) for key, value in obj.items()}
    if isinstance(obj, list):
        return [sanitize(value) for value in obj]
    return obj


def utc_now_iso() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")


# ===================== auth =====================


def build_auth_header() -> str:
    """Return the Authorization header value: pasted token if provided, else mint one."""
    pasted = os.environ.get(AUTH_TOKEN_ENV, "").strip()
    if pasted:
        return pasted if pasted.lower().startswith("bearer ") else f"Bearer {pasted}"

    if not JWT_PRIVATE_KEY_PATH.exists():
        raise SystemExit(
            f"No bearer token available.\n"
            f"- Set {AUTH_TOKEN_ENV}=<jwt>, or\n"
            f"- generate signing keys with ./scripts.sh setup "
            f"(expected key at {JWT_PRIVATE_KEY_PATH})."
        )
    try:
        from jose import jwt as jose_jwt
    except ImportError as exc:
        raise SystemExit(
            "python-jose is required to mint tokens: pip install 'python-jose[cryptography]'"
        ) from exc

    claims = {
        "sub": JWT_SUBJECT,
        "email": f"{JWT_SUBJECT}@bench.local",
        "name": "Benchmark Runner",
        ROLE_CLAIM: "Admin",
        "iat": int(time.time()),
        "exp": int(time.time()) + JWT_TTL_SECONDS,
        "aud": JWT_AUDIENCE,
        "iss": JWT_ISSUER,
    }
    private_key = JWT_PRIVATE_KEY_PATH.read_text()
    return "Bearer " + jose_jwt.encode(claims, private_key, algorithm="RS256")


# ===================== backend stage calls =====================


async def embed_query(client: httpx.AsyncClient, query: str) -> tuple[list[float], float]:
    """Embed via Ollama exactly like EmbeddingClient does. Returns (vector, elapsed_ms)."""
    started = time.perf_counter()
    resp = await client.post(
        f"{OLLAMA_URL}/api/embeddings",
        json={"model": EMBEDDING_MODEL, "prompt": query, "keep_alive": 3600},
    )
    resp.raise_for_status()
    elapsed = (time.perf_counter() - started) * 1000.0
    return resp.json()["embedding"], elapsed


async def qdrant_ticket_search(
    client: httpx.AsyncClient, vector: list[float], limit: int
) -> tuple[list[dict], float]:
    """Closed-ticket search replicating VectorStore.search + SimilarityService filter."""
    started = time.perf_counter()
    resp = await client.post(
        f"{QDRANT_URL}/collections/{COLLECTION_NAME}/points/query",
        json={"query": vector, "limit": limit, "filter": TICKET_FILTER, "with_payload": True},
    )
    resp.raise_for_status()
    elapsed = (time.perf_counter() - started) * 1000.0
    return resp.json()["result"]["points"], elapsed


# ===================== preflight =====================


def normalize_model_name(name: str) -> str:
    return name if ":" in name else f"{name}:latest"


async def preflight(
    client: httpx.AsyncClient, *, need_ai: bool, need_embed: bool, need_chat_model: bool
) -> None:
    problems: list[str] = []

    if need_ai:
        try:
            resp = await client.get(f"{AI_BASE_URL}/health/ready")
            if resp.status_code != 200:
                problems.append(f"AI service {AI_BASE_URL} not ready (HTTP {resp.status_code})")
        except httpx.HTTPError as exc:
            problems.append(f"AI service unreachable at {AI_BASE_URL}: {exc!r}")

    try:
        if need_embed or need_chat_model:
            tags = (await client.get(f"{OLLAMA_URL}/api/tags")).json().get("models", [])
            present = {normalize_model_name(m.get("name", "")) for m in tags}
            wanted = ([EMBEDDING_MODEL] if need_embed else []) + (
                [CHAT_MODEL] if need_chat_model else []
            )
            for model in wanted:
                if normalize_model_name(model) not in present:
                    problems.append(
                        f"Ollama model '{model}' not pulled yet "
                        f"(ai-service pulls models on startup; check its logs)"
                    )
    except httpx.HTTPError as exc:
        problems.append(f"Ollama unreachable at {OLLAMA_URL}: {exc!r}")

    try:
        resp = await client.get(f"{QDRANT_URL}/collections/{COLLECTION_NAME}")
        if resp.status_code == 404:
            problems.append(
                f"Qdrant collection '{COLLECTION_NAME}' does not exist yet - create tickets, "
                f"then POST /api/ai/reindex-tickets (or use --reindex-tickets)"
            )
        elif resp.status_code != 200:
            problems.append(f"Qdrant collection lookup failed (HTTP {resp.status_code})")
    except httpx.HTTPError as exc:
        problems.append(f"Qdrant unreachable at {QDRANT_URL}: {exc!r}")

    if problems:
        raise SystemExit("Preflight failed:\n  - " + "\n  - ".join(problems))


# ===================== latency: sequential + stage breakdown =====================


async def run_sequential_latency(
    client: httpx.AsyncClient, auth_header: str, n_requests: int, warmup: int
) -> tuple[list[dict], dict[str, dict]]:
    rows: list[dict] = []
    errors = 0

    if warmup:
        print(f"warmup: discarding {warmup} requests (model load / connection setup)")
        for i in range(warmup):
            query = QUERY_POOL[i % len(QUERY_POOL)]
            try:
                vector, _ = await embed_query(client, query)
                await qdrant_ticket_search(client, vector, 1)
                await client.post(
                    f"{AI_BASE_URL}/api/ai/similar-tickets",
                    json={"query": query},
                    headers={"Authorization": auth_header},
                )
            except httpx.HTTPError:
                continue

    print(f"sequential: {n_requests} requests, each timed end-to-end plus out-of-band stages")
    for i in range(n_requests):
        query = QUERY_POOL[i % len(QUERY_POOL)]
        try:
            vector, embed_ms = await embed_query(client, query)
            _, search_ms = await qdrant_ticket_search(client, vector, SIMILAR_SCAN)
            req_started = time.perf_counter()
            resp = await client.post(
                f"{AI_BASE_URL}/api/ai/similar-tickets",
                json={"query": query},
                headers={"Authorization": auth_header},
            )
            e2e_ms = (time.perf_counter() - req_started) * 1000.0
        except httpx.HTTPError:
            errors += 1
            continue
        if resp.status_code != 200:
            errors += 1
            continue
        rows.append(
            {
                "index": i,
                "query": query,
                "e2e_ms": round(e2e_ms, 2),
                "embed_ms": round(embed_ms, 2),
                "qdrant_ms": round(search_ms, 2),
                "overhead_ms": round(max(0.0, e2e_ms - embed_ms - search_ms), 2),
                "num_results": len(resp.json()),
            }
        )
        if (i + 1) % 50 == 0 or i + 1 == n_requests:
            print(f"  {i + 1}/{n_requests} done ({errors} errors)")

    stages = {
        "endpoint e2e": [row["e2e_ms"] for row in rows],
        "embed (ollama)": [row["embed_ms"] for row in rows],
        "qdrant search": [row["qdrant_ms"] for row in rows],
        "overhead (app+net)": [row["overhead_ms"] for row in rows],
    }
    stats = {name: latency_stats(values) for name, values in stages.items()}
    print_table(
        f"LATENCY sequential ({len(rows)} ok, {errors} errors)",
        ["stage", "mean ms", "p50 ms", "p95 ms", "p99 ms", "max ms"],
        [
            [name] + [stat[key] for key in ("mean_ms", "p50_ms", "p95_ms", "p99_ms", "max_ms")]
            for name, stat in stats.items()
        ],
    )
    return rows, stats


# ===================== latency: LLM generation probe (RAG chat) =====================


async def chat_probe_once(
    client: httpx.AsyncClient, auth_header: str, question: str
) -> dict | None:
    """Stream one RAG chat answer; returns ttft/total/token counts, or None on failure."""
    started = time.perf_counter()
    ttft_ms: float | None = None
    tokens = 0
    try:
        async with client.stream(
            "POST",
            f"{AI_BASE_URL}/api/ai/chat",
            json={"message": question},
            headers={"Authorization": auth_header},
        ) as resp:
            if resp.status_code != 200:
                return None
            current_event = ""
            async for line in resp.aiter_lines():
                if line.startswith("event:"):
                    current_event = line[len("event:"):].strip()
                elif line.startswith("data:"):
                    if current_event == "token":
                        if ttft_ms is None:
                            ttft_ms = (time.perf_counter() - started) * 1000.0
                        tokens += 1
                    elif current_event == "error":
                        return None
                    elif current_event == "done":
                        break
    except httpx.HTTPError:
        return None
    if ttft_ms is None:
        return None
    total_ms = (time.perf_counter() - started) * 1000.0
    return {"ttft_ms": round(ttft_ms, 2), "total_ms": round(total_ms, 2), "tokens": tokens}


async def run_chat_latency_probe(
    client: httpx.AsyncClient, auth_header: str, n_requests: int
) -> tuple[list[dict], dict[str, dict]]:
    rows: list[dict] = []
    errors = 0
    print(f"chat generation probe: {n_requests} streamed answers ({CHAT_MODEL})")
    print("stage attribution: retrieval timed out-of-band (same replay trick as sequential)")
    for i in range(n_requests):
        question = QUERY_POOL[i % len(QUERY_POOL)]
        try:
            vector, embed_ms = await embed_query(client, question)
            _, search_ms = await qdrant_ticket_search(client, vector, SIMILAR_SCAN)
        except httpx.HTTPError:
            embed_ms = search_ms = None
        result = await chat_probe_once(client, auth_header, question)
        if result is None:
            errors += 1
        else:
            result["embed_ms"] = round(embed_ms, 2) if embed_ms is not None else None
            result["qdrant_ms"] = round(search_ms, 2) if search_ms is not None else None
            result["gen_tail_ms"] = round(result["total_ms"] - result["ttft_ms"], 2)
            rows.append(result)
        if (i + 1) % 10 == 0 or i + 1 == n_requests:
            print(f"  {i + 1}/{n_requests} done ({errors} errors)")

    stats = {
        "total stream time": latency_stats([row["total_ms"] for row in rows]),
        "time-to-first-token": latency_stats([row["ttft_ms"] for row in rows]),
        "generation tail (total-TTFT)": latency_stats([row["gen_tail_ms"] for row in rows]),
    }
    replay = [
        row["embed_ms"] + row["qdrant_ms"]
        for row in rows
        if row["embed_ms"] is not None and row["qdrant_ms"] is not None
    ]
    stats["retrieval replay (embed+qdrant)"] = latency_stats(replay)
    print_table(
        f"LLM GENERATION via /api/ai/chat ({len(rows)} ok)",
        ["metric", "mean ms", "p50 ms", "p95 ms", "p99 ms", "max ms"],
        [
            [name] + [stat[key] for key in ("mean_ms", "p50_ms", "p95_ms", "p99_ms", "max_ms")]
            for name, stat in stats.items()
        ],
    )
    totals = [row["total_ms"] for row in rows]
    if totals:
        gen_rate = sum(row["tokens"] for row in rows) / (sum(totals) / 1000.0)
        print(f"aggregate generation throughput: {gen_rate:.1f} tokens/s across all streams")
    return rows, stats


# ===================== load test =====================


async def stream_chat_once(
    client: httpx.AsyncClient, auth_header: str, message: str
) -> tuple[bool, int]:
    """Stream one /api/ai/chat answer; returns (completed_ok, token_event_count)."""
    try:
        async with client.stream(
            "POST",
            f"{AI_BASE_URL}/api/ai/chat",
            json={"message": message},
            headers={"Authorization": auth_header},
        ) as resp:
            if resp.status_code != 200:
                return False, 0
            current_event = ""
            tokens = 0
            async for line in resp.aiter_lines():
                if line.startswith("event:"):
                    current_event = line[len("event:"):].strip()
                elif line.startswith("data:") and current_event == "token":
                    tokens += 1
                elif current_event == "error":
                    return False, tokens
                elif current_event == "done":
                    return True, tokens
            return False, tokens
    except httpx.HTTPError:
        return False, 0


async def load_worker(
    client: httpx.AsyncClient,
    auth_header: str,
    deadline: float,
    start_signal: asyncio.Event,
    lock: asyncio.Lock,
    latencies: list[float],
    counters: dict,
    endpoint: str = "similar",
) -> None:
    await start_signal.wait()
    while time.perf_counter() < deadline:
        req_started = time.perf_counter()
        ok = False
        n_tokens = 0
        query = QUERY_POOL[random.randrange(len(QUERY_POOL))]
        try:
            if endpoint == "chat":
                ok, n_tokens = await stream_chat_once(client, auth_header, query)
            else:
                resp = await client.post(
                    f"{AI_BASE_URL}/api/ai/similar-tickets",
                    json={"query": query},
                    headers={"Authorization": auth_header},
                )
                ok = resp.status_code == 200
        except httpx.HTTPError:
            ok = False
        elapsed = (time.perf_counter() - req_started) * 1000.0
        async with lock:
            if ok:
                latencies.append(elapsed)
                counters["tokens"] = counters.get("tokens", 0) + n_tokens
            else:
                counters["errors"] += 1


async def run_load_test(
    client: httpx.AsyncClient,
    auth_header: str,
    levels: list[int],
    duration_s: float,
    endpoints: list[str],
) -> tuple[list[dict], list[dict]]:
    summary: list[dict] = []
    raw_rows: list[dict] = []

    for endpoint in endpoints:
        for level in levels:
            latencies: list[float] = []
            counters = {"errors": 0}
            lock = asyncio.Lock()
            start_signal = asyncio.Event()
            deadline = time.perf_counter() + duration_s

            tasks = [
                asyncio.create_task(
                    load_worker(
                        client, auth_header, deadline, start_signal, lock, latencies,
                        counters, endpoint,
                    )
                )
                for _ in range(level)
            ]
            start_signal.set()
            wall_started = time.perf_counter()
            await asyncio.gather(*tasks)
            wall_s = max(time.perf_counter() - wall_started, duration_s)
            errors = counters["errors"]

            rps = len(latencies) / wall_s if wall_s > 0 else float("nan")
            stats = latency_stats(latencies)
            row = {
                "endpoint": endpoint,
                "concurrency": level,
                "duration_s": round(wall_s, 2),
                "completed": len(latencies),
                "errors": errors,
                "achieved_rps": round(rps, 2),
                **stats,
            }
            if endpoint == "chat":
                tokens_per_s = counters.get("tokens", 0) / wall_s if wall_s > 0 else float("nan")
                row["tokens_per_s"] = round(tokens_per_s, 1)
            summary.append(row)
            raw_rows.extend(
                {"endpoint": endpoint, "concurrency": level, "latency_ms": round(value, 2)}
                for value in latencies
            )
            tok_cell = f" | {row.get('tokens_per_s', '-'):>7} tok/s" if endpoint == "chat" else ""
            print(
                f"  [{endpoint:>7}] concurrency {level:>3}: {rps:7.1f} req/s | p50 {stats['p50_ms']:>8.1f} ms"
                f" | p95 {stats['p95_ms']:>8.1f} ms | errors {errors}{tok_cell}"
            )

    print_table(
        f"LOAD TEST sustained ~{duration_s:.0f}s per level (endpoint e2e)",
        ["endpoint", "concurrency", "req/s", "completed", "errors", "tok/s",
         "p50 ms", "p95 ms", "p99 ms", "max ms"],
        [
            [
                row["endpoint"],
                row["concurrency"],
                row["achieved_rps"],
                row["completed"],
                row["errors"],
                row.get("tokens_per_s", "-"),
                row["p50_ms"],
                row["p95_ms"],
                row["p99_ms"],
                row["max_ms"],
            ]
            for row in summary
        ],
    )
    return summary, raw_rows


# ===================== quality: eval set + metrics =====================


async def fetch_closed_tickets(client: httpx.AsyncClient, max_points: int) -> list[dict]:
    """Scroll closed-ticket points from Qdrant; returns one deduped summary per ticket."""
    tickets: list[dict] = []
    seen_ids: set[str] = set()
    offset = None
    while len(tickets) < max_points:
        body: dict = {
            "filter": TICKET_FILTER,
            "limit": min(250, max_points - len(tickets)),
            "with_payload": True,
        }
        if offset is not None:
            body["offset"] = offset
        resp = await client.post(
            f"{QDRANT_URL}/collections/{COLLECTION_NAME}/points/scroll", json=body
        )
        resp.raise_for_status()
        result = resp.json()["result"]
        for point in result.get("points", []):
            payload = point.get("payload") or {}
            doc_id = str(payload.get("doc_id") or "")
            title = str(payload.get("title") or "")
            if doc_id and title and doc_id not in seen_ids:
                seen_ids.add(doc_id)
                tickets.append(
                    {
                        "doc_id": doc_id,
                        "reference_number": payload.get("reference_number"),
                        "title": title,
                    }
                )
        offset = result.get("next_page_offset")
        if offset is None:
            break
    return tickets


async def generate_paraphrase(client: httpx.AsyncClient, title: str) -> tuple[str, str]:
    """Paraphrase a ticket title as an end-user query. Returns (query, source)."""
    prompt = (
        "Rewrite the following IT support ticket title as one informal sentence, phrased "
        "the way an end user would describe the problem when asking IT support for help. "
        "Use different wording than the original where possible. Reply with ONLY the "
        f"rewritten sentence.\n\nTicket title: \"{title}\""
    )
    try:
        resp = await client.post(
            f"{OLLAMA_URL}/api/generate",
            json={
                "model": CHAT_MODEL,
                "prompt": prompt,
                "stream": False,
                "options": {"temperature": 0.8, "num_predict": 60},
            },
            timeout=60.0,
        )
        resp.raise_for_status()
        text = str(resp.json().get("response", "")).strip().strip('"').strip("'")
        text = text.splitlines()[0].strip() if text else ""
        text = text[:250]
        if len(text) >= 8:
            return text, "llm_paraphrase"
    except httpx.HTTPError:
        pass
    return title, "title_fallback"


async def build_eval_set(
    client: httpx.AsyncClient, size: int, regen: bool, eval_path: Path
) -> tuple[list[dict], bool]:
    """Load cached eval pairs, or generate them from closed tickets in the index."""
    if eval_path.exists() and not regen:
        pairs = [json.loads(line) for line in eval_path.read_text().splitlines() if line.strip()]
        print(f"eval set: loaded {len(pairs)} cached pairs from {eval_path}")
        return pairs, False

    all_tickets = await fetch_closed_tickets(client, max_points=5000)
    if not all_tickets:
        raise SystemExit(
            "No CLOSED tickets found in the index - quality eval needs closed tickets. "
            "Create tickets, close some, then POST /api/ai/reindex-tickets."
        )
    if len(all_tickets) < size:
        print(f"warning: only {len(all_tickets)} closed tickets available, reducing eval size")
        size = len(all_tickets)
    sampled = random.sample(all_tickets, size)

    print(f"eval set: generating {size} paraphrased queries via {CHAT_MODEL}")
    pairs: list[dict] = []
    for i, ticket in enumerate(sampled):
        query, source = await generate_paraphrase(client, ticket["title"])
        pairs.append(
            {
                "query": query,
                "expected_doc_id": ticket["doc_id"],
                "expected_reference_number": ticket["reference_number"],
                "source_title": ticket["title"],
                "source": source,
            }
        )
        if (i + 1) % 10 == 0 or i + 1 == size:
            print(f"  {i + 1}/{size} generated")

    eval_path.parent.mkdir(parents=True, exist_ok=True)
    eval_path.write_text("".join(json.dumps(pair) + "\n" for pair in pairs), encoding="utf-8")
    print(f"eval set: cached {len(pairs)} pairs to {eval_path} (edit freely, rerun to rescore)")
    return pairs, True


async def run_quality_eval(
    client: httpx.AsyncClient, size: int, regen: bool, eval_path: Path
) -> tuple[dict | None, list[dict]]:
    pairs, generated = await build_eval_set(client, size, regen, eval_path)
    if not pairs:
        return None, []

    detail: list[dict] = []
    ranks: list[int | None] = []
    for i, pair in enumerate(pairs):
        try:
            vector, _ = await embed_query(client, pair["query"])
            points, _ = await qdrant_ticket_search(client, vector, SIMILAR_SCAN)
        except httpx.HTTPError as exc:
            print(f"  pair {i + 1}: backend error ({exc!r}), skipping")
            continue

        best_by_doc: dict[str, float] = {}
        titles_by_doc: dict[str, str] = {}
        for point in points:
            payload = point.get("payload") or {}
            doc_id = str(payload.get("doc_id") or "")
            if not doc_id:
                continue
            score = float(point.get("score") or 0.0)
            if doc_id not in best_by_doc or score > best_by_doc[doc_id]:
                best_by_doc[doc_id] = score
                titles_by_doc[doc_id] = str(payload.get("title") or "")
        ranked = sorted(best_by_doc, key=lambda doc: best_by_doc[doc], reverse=True)

        expected = pair["expected_doc_id"]
        rank = ranked.index(expected) + 1 if expected in ranked else None
        ranks.append(rank)
        top_entries = [
            {"ref": titles_by_doc[doc][:80], "score": round(best_by_doc[doc], 4)}
            for doc in ranked[:3]
        ]
        flat_top = {
            f"top{i}_{field}": value
            for i, entry in enumerate(top_entries, start=1)
            for field, value in entry.items()
        }
        detail.append(
            {
                "query": pair["query"],
                "expected_reference_number": pair.get("expected_reference_number"),
                "rank": rank,
                "top3": top_entries,
                **flat_top,
            }
        )
        if (i + 1) % 20 == 0 or i + 1 == len(pairs):
            print(f"  scored {i + 1}/{len(pairs)}")

    total = len(ranks)
    if total == 0:
        print("quality eval: no pairs could be scored")
        return None, []

    table_rows = []
    metrics: dict = {}
    for k in K_VALUES:
        hits = sum(1 for rank in ranks if rank is not None and rank <= k)
        recall = hits / total
        precision_at_k = hits / (total * k)
        metrics[f"recall@{k}"] = round(recall, 4)
        metrics[f"precision@{k}"] = round(precision_at_k, 4)
        table_rows.append([k, f"{recall * 100:.1f}% ({hits}/{total})", f"{precision_at_k * 100:.1f}%"])
    mrr = sum((1.0 / rank if rank else 0.0) for rank in ranks) / total
    metrics["mrr"] = round(mrr, 4)

    print_table(
        f"RETRIEVAL QUALITY ({total} pairs, single relevant ticket each: recall@k == hit-rate@k)",
        ["k", "recall@k (hit rate)", "precision@k"],
        table_rows,
    )
    print(f"Mean Reciprocal Rank (MRR): {mrr:.3f}")
    misses = [item for item in detail if item["rank"] is None]
    if misses:
        print(f"misses (expected ticket not in top-{max(K_VALUES)}): {len(misses)}/{total}")
        for item in misses[:5]:
            print(
                f"  expected {item['expected_reference_number']} for: {item['query'][:70]!r}"
            )

    return {"pairs": total, "generated_now": generated, **metrics}, detail


# ===================== scale =====================


def growth_since(
    data: list[list[str]], now: datetime, days: int, current_total: int
) -> tuple[int, str] | None:
    """Delta vs the newest recorded run at least `days` old; None when history is too short."""
    cutoff = now - timedelta(days=days)
    snapshots: list[tuple[datetime, int]] = []
    for row in data:
        if len(row) < 2 or not row[1].isdigit():
            continue
        try:
            stamp = datetime.fromisoformat(row[0])
        except ValueError:
            continue
        if stamp <= cutoff:
            snapshots.append((stamp, int(row[1])))
    if not snapshots:
        return None
    stamp, past_total = max(snapshots, key=lambda entry: entry[0])
    return current_total - past_total, stamp.isoformat(timespec="seconds")


async def run_scale_check(client: httpx.AsyncClient) -> dict:
    info = (await client.get(f"{QDRANT_URL}/collections/{COLLECTION_NAME}")).json()["result"]
    total = info.get("points_count")

    breakdown: dict[str, int] = {}
    for doc_type in DOC_TYPES:
        resp = await client.post(
            f"{QDRANT_URL}/collections/{COLLECTION_NAME}/points/count",
            json={"filter": {"must": [{"key": "doc_type", "match": {"value": doc_type}}]}},
        )
        breakdown[doc_type] = int(resp.json()["result"]["count"])

    if total is None:
        total = sum(breakdown.values())

    print_table(
        f"INDEX SIZE collection '{COLLECTION_NAME}' (status: {info.get('status')})",
        ["metric", "points"],
        [["total", total]] + [[f"doc_type={name}", count] for name, count in breakdown.items()],
    )

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    first_row: list[str] | None = None
    previous_row: list[str] | None = None
    data: list[list[str]] = []
    if SCALE_HISTORY_PATH.exists():
        with SCALE_HISTORY_PATH.open(newline="", encoding="utf-8") as handle:
            existing = [row for row in csv.reader(handle) if row]
        data = existing[1:] if existing else []
        if data:
            first_row, previous_row = data[0], data[-1]
            print_table(
                f"SCALE HISTORY ({len(data)} prior runs)",
                ["timestamp_utc", "total", "tickets", "comments", "kb"],
                [row[:5] for row in data[-10:]],
            )

    write_header = not SCALE_HISTORY_PATH.exists() or SCALE_HISTORY_PATH.stat().st_size == 0
    with SCALE_HISTORY_PATH.open("a", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        if write_header:
            writer.writerow(["timestamp_utc", "points_total", "tickets", "comments", "kb_articles"])
        writer.writerow([utc_now_iso(), total, breakdown["ticket"], breakdown["comment"], breakdown["kb"]])
    print(f"scale history appended to {SCALE_HISTORY_PATH}")

    deltas: dict[str, int | None] = {}
    if isinstance(total, int):
        if previous_row and previous_row[1].isdigit():
            print(f"growth vs previous run: {total - int(previous_row[1]):+d} points")
        if first_row and first_row is not previous_row and first_row[1].isdigit():
            print(f"growth since first recorded run ({first_row[0]}): {total - int(first_row[1]):+d} points")
        now = datetime.now(UTC)
        for days in (7, 30):
            outcome = growth_since(data, now, days, total)
            if outcome is None:
                deltas[f"points_{days}d_delta"] = None
                print(f"growth over last {days} days: no recorded run >= {days} days old yet")
            else:
                change, snapshot = outcome
                deltas[f"points_{days}d_delta"] = change
                print(f"growth over last {days} days: {change:+d} points (snapshot {snapshot})")
    return {"total": total, **breakdown, **deltas}


# ===================== orchestration =====================


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--sections", default="latency,load,quality,scale",
                        help="comma-separated subset of latency,load,quality,scale")
    parser.add_argument("--seq-requests", type=int, default=SEQ_REQUESTS)
    parser.add_argument("--warmup", type=int, default=WARMUP_REQUESTS)
    parser.add_argument("--chat-requests", type=int, default=CHAT_PROBE_REQUESTS,
                        help="streamed /api/ai/chat probes for LLM-stage timing (0 skips)")
    parser.add_argument("--levels", type=str, default=",".join(map(str, CONCURRENCY_LEVELS)),
                        help="comma-separated concurrency levels, e.g. 10,25,50")
    parser.add_argument("--load-endpoint", type=str, default=",".join(LOAD_ENDPOINTS),
                        help="comma-separated subset of similar,chat the load section hits")
    parser.add_argument("--load-duration", type=float, default=LOAD_DURATION_SECONDS)
    parser.add_argument("--eval-size", type=int, default=EVAL_SET_SIZE)
    parser.add_argument("--eval-set", type=Path, default=EVAL_SET_PATH,
                        help="path to the (query, expected_ticket_id) pairs file")
    parser.add_argument("--regen-eval-set", action="store_true",
                        help="discard the cached eval_set.jsonl and regenerate pairs")
    parser.add_argument("--reindex-tickets", action="store_true",
                        help="POST /api/ai/reindex-tickets (Admin) before benchmarking")
    parser.add_argument("--seed", type=int, default=RANDOM_SEED)
    return parser.parse_args()


async def main() -> None:
    args = parse_args()
    random.seed(args.seed)
    sections = {part.strip() for part in args.sections.split(",") if part.strip()}
    unknown = sections - {"latency", "load", "quality", "scale"}
    if unknown:
        raise SystemExit(f"unknown sections: {', '.join(sorted(unknown))}")

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    run_stamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")

    timeout = httpx.Timeout(REQUEST_TIMEOUT_SECONDS, connect=10.0)
    load_endpoints = [ep.strip() for ep in args.load_endpoint.split(",") if ep.strip()]
    unknown_endpoints = set(load_endpoints) - {"similar", "chat"}
    if unknown_endpoints:
        raise SystemExit(
            f"unknown load endpoints: {', '.join(sorted(unknown_endpoints))} (valid: similar, chat)"
        )
    async with httpx.AsyncClient(timeout=timeout, limits=httpx.Limits(max_connections=110)) as client:
        need_ai = bool(sections & {"latency", "load"})
        need_embed = need_ai or "quality" in sections
        need_chat = ("latency" in sections and args.chat_requests > 0) or (
            "load" in sections and "chat" in load_endpoints
        )
        await preflight(client, need_ai=need_ai, need_embed=need_embed, need_chat_model=need_chat)

        results: dict = {
            "started_at": utc_now_iso(),
            "config": {
                "ai_base_url": AI_BASE_URL,
                "ollama_url": OLLAMA_URL,
                "qdrant_url": QDRANT_URL,
                "collection": COLLECTION_NAME,
                "embedding_model": EMBEDDING_MODEL,
                "chat_model": CHAT_MODEL,
                "similar_scan": SIMILAR_SCAN,
                "seq_requests": args.seq_requests,
                "chat_requests": args.chat_requests,
                "levels": args.levels,
                "load_endpoints": load_endpoints,
                "load_duration_s": args.load_duration,
                "eval_size": args.eval_size,
                "seed": args.seed,
            },
        }

        auth_header = build_auth_header() if (need_ai or args.reindex_tickets) else ""
        token_preview = (auth_header[:20] + "...") if auth_header else "(not needed)"
        print(f"auth: {token_preview}")

        if args.reindex_tickets:
            print("reindexing tickets via /api/ai/reindex-tickets ...")
            resp = await client.post(
                f"{AI_BASE_URL}/api/ai/reindex-tickets",
                headers={"Authorization": auth_header},
                timeout=900.0,
            )
            if resp.status_code == 200:
                print(f"reindexed {resp.json()['indexed']} tickets")
            else:
                print(f"reindex failed (HTTP {resp.status_code}): {resp.text[:200]}")

        if "latency" in sections:
            seq_rows, seq_stats = await run_sequential_latency(
                client, auth_header, args.seq_requests, args.warmup
            )
            chat_rows, chat_stats = [], {}
            if args.chat_requests > 0:
                chat_rows, chat_stats = await run_chat_latency_probe(
                    client, auth_header, args.chat_requests
                )
            results["latency"] = {
                "sequential_summary": seq_stats,
                "chat_summary": chat_stats,
            }
            results["_raw_seq"] = seq_rows
            results["_raw_chat"] = chat_rows

        if "load" in sections:
            levels = [int(level) for level in args.levels.split(",") if level.strip()]
            load_summary, load_raw = await run_load_test(
                client, auth_header, levels, args.load_duration, load_endpoints
            )
            results["load"] = {"summary": load_summary}
            results["_raw_load"] = load_raw

        if "quality" in sections:
            quality_summary, quality_detail = await run_quality_eval(
                client, args.eval_size, args.regen_eval_set, args.eval_set
            )
            results["quality"] = quality_summary or {}
            results["_quality_detail"] = quality_detail

        if "scale" in sections:
            results["scale"] = await run_scale_check(client) or {}

        results["finished_at"] = utc_now_iso()

    json_path = RESULTS_DIR / f"run_{run_stamp}.json"
    json_path.write_text(json.dumps(sanitize(results), indent=2), encoding="utf-8")

    csv_specs = [
        ("_raw_seq", f"latency_raw_{run_stamp}.csv",
         ["index", "query", "e2e_ms", "embed_ms", "qdrant_ms", "overhead_ms", "num_results"]),
        ("_raw_chat", f"chat_raw_{run_stamp}.csv",
         ["ttft_ms", "total_ms", "tokens", "gen_tail_ms", "embed_ms", "qdrant_ms"]),
        ("_raw_load", f"load_raw_{run_stamp}.csv",
         ["endpoint", "concurrency", "latency_ms"]),
        ("_quality_detail", f"quality_detail_{run_stamp}.csv",
         ["query", "expected_reference_number", "rank",
          "top1_ref", "top1_score", "top2_ref", "top2_score", "top3_ref", "top3_score"]),
    ]
    written = [str(json_path)]
    for key, filename, fieldnames in csv_specs:
        rows = results.pop(key, [])
        if not rows:
            continue
        path = RESULTS_DIR / filename
        with path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=fieldnames, extrasaction="ignore")
            writer.writeheader()
            writer.writerows(rows)
        written.append(str(path))

    print("\nartifacts written:")
    for path in written:
        print(f"  {path}")


if __name__ == "__main__":
    asyncio.run(main())
